-- Seed data for Dreamcatcher: groups, idols, positions, albums, songs
-- Generated from the local development database. Idempotent (ON CONFLICT DO NOTHING)
-- so it is safe to run on a fresh deployment and on an already-seeded database.

CREATE SCHEMA IF NOT EXISTS api;

-- groups
INSERT INTO api.groups (group_id, group_name, agency_name, concept, group_image) OVERRIDING SYSTEM VALUE VALUES (1, 'Dreamcatcher', 'Dreamcatcher Company', 'Rock & Dark Fantasy', '/images/dreamcatcher/dreamcatcher_logo.jpg') ON CONFLICT DO NOTHING;
-- albums
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (1, 'Why Did You Come To My Home?', 1, 2, 2014, 'Single', '/images/dreamcatcher/albums/album1.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (2, 'Love Shake', 1, 6, 2014, 'EP', '/images/dreamcatcher/albums/album2.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (3, 'Nightmare', 1, 4, 2017, 'Single', '/images/dreamcatcher/albums/album3.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (4, 'Fall Asleep in the Mirror', 1, 4, 2017, 'Single', '/images/dreamcatcher/albums/album4.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (5, 'Prequel', 1, 6, 2017, 'EP', '/images/dreamcatcher/albums/album5.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (6, 'Full Moon', 1, 2, 2018, 'Single', '/images/dreamcatcher/albums/album6.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (7, 'Escape the ERA', 1, 6, 2018, 'EP', '/images/dreamcatcher/albums/album7.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (8, 'Alone In The City', 1, 6, 2018, 'EP', '/images/dreamcatcher/albums/album8.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (9, 'What -Japanese Ver.-', 1, 3, 2018, 'Single', '/images/dreamcatcher/albums/album9.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (10, 'Over the Sky', 1, 2, 2019, 'Single', '/images/dreamcatcher/albums/album10.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (11, 'The End of Nightmare', 1, 6, 2019, 'EP', '/images/dreamcatcher/albums/album11.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (12, 'PIRI ~ 笛を吹け ~ -Japanese Ver.-', 1, 3, 2019, 'Single', '/images/dreamcatcher/albums/album12.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (13, 'The Beginning of the End', 1, 12, 2019, 'Studio', '/images/dreamcatcher/albums/album13.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (14, 'Raid of Dream', 1, 6, 2019, 'EP', '/images/dreamcatcher/albums/album14.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (15, 'Dystopia: The Tree of Language', 1, 14, 2020, 'Studio', '/images/dreamcatcher/albums/album15.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (16, 'Endless Night', 1, 3, 2020, 'Single', '/images/dreamcatcher/albums/album16.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (17, 'Be The Future', 1, 2, 2020, 'Single', '/images/dreamcatcher/albums/album17.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (18, 'R.o.S.E BLUE', 1, 2, 2020, 'Single', '/images/dreamcatcher/albums/album18.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (19, 'Dystopia: Lose Myself', 1, 6, 2020, 'EP', '/images/dreamcatcher/albums/album19.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (20, 'No More', 1, 1, 2020, 'Single', '/images/dreamcatcher/albums/album20.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (21, 'Eclipse (TV Size)', 1, 1, 2020, 'Single', '/images/dreamcatcher/albums/album21.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (22, 'Dystopia: Road to Utopia', 1, 7, 2021, 'EP', '/images/dreamcatcher/albums/album22.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (23, 'Eclipse', 1, 6, 2021, 'Single', '/images/dreamcatcher/albums/album23.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (24, 'Shadow', 1, 2, 2021, 'Single', '/images/dreamcatcher/albums/album24.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (25, 'Summer Holiday', 1, 6, 2021, 'EP', '/images/dreamcatcher/albums/album25.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (26, 'Apocalypse: Save Us', 1, 14, 2022, 'Studio', '/images/dreamcatcher/albums/album26.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (27, 'Apocalypse: Follow Us', 1, 6, 2022, 'EP', '/images/dreamcatcher/albums/album27.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (28, 'Reason', 1, 2, 2023, 'Single', '/images/dreamcatcher/albums/album28.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (29, 'Apocalypse: From Us', 1, 5, 2023, 'EP', '/images/dreamcatcher/albums/album29.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (30, 'BONVOYAGE (Farewell Ver.)', 1, 1, 2023, 'Single', '/images/dreamcatcher/albums/album30.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (31, 'VillainS', 1, 5, 2023, 'EP', '/images/dreamcatcher/albums/album31.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (32, 'Luck Inside 7 Doors (2024 Concert Ver.)', 1, 2, 2024, 'Single', '/images/dreamcatcher/albums/album32.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (33, 'VirtuouS', 1, 5, 2024, 'EP', '/images/dreamcatcher/albums/album33.jpeg') ON CONFLICT DO NOTHING;
INSERT INTO api.albums (album_id, album_title, group_id, track_count, release_date, album_type, album_image) OVERRIDING SYSTEM VALUE VALUES (34, 'My Christmas Sweet Love', 1, 3, 2024, 'Single', '/images/dreamcatcher/albums/album34.jpeg') ON CONFLICT DO NOTHING;
-- idols
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (1, 'Kim Minji', 'JiU', 1, 'Nightmare of being chased', '/images/dreamcatcher/idols/jiu.png') ON CONFLICT DO NOTHING;
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (2, 'Kim Bora', 'SuA', 1, 'Nightmare of being unable to move', '/images/dreamcatcher/idols/sua.png') ON CONFLICT DO NOTHING;
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (3, 'Lee Siyeon', 'Siyeon', 1, 'Nightmare of being locked in a narrow space', '/images/dreamcatcher/idols/siyeon.png') ON CONFLICT DO NOTHING;
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (4, 'Han Dong', 'Handong', 1, 'Nightmare of being watched', '/images/dreamcatcher/idols/handong.png') ON CONFLICT DO NOTHING;
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (5, 'Kim Yoohyeon', 'Yoohyeon', 1, 'Nightmare of being lost in a strange place', '/images/dreamcatcher/idols/yoohyeon.png') ON CONFLICT DO NOTHING;
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (6, 'Lee Yubin', 'Dami', 1, 'Nightmare of being hurt', '/images/dreamcatcher/idols/dami.png') ON CONFLICT DO NOTHING;
INSERT INTO api.idols (idol_id, real_name, stage_name, group_id, lore_concept, image_url) OVERRIDING SYSTEM VALUE VALUES (7, 'Lee Ga Hyun', 'Gahyun', 1, 'Nightmare of falling from a high place', '/images/dreamcatcher/idols/gahyun.png') ON CONFLICT DO NOTHING;
-- positions
INSERT INTO api.positions (position_id, name, category) VALUES (1, 'Main Vocalist', 'Vocal') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (2, 'Lead Vocalist', 'Vocal') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (3, 'Sub Vocalist', 'Vocal') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (4, 'Main Dancer', 'Dance') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (5, 'Lead Dancer', 'Dance') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (6, 'Sub Dancer', 'Dance') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (7, 'Main Rapper', 'Rap') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (8, 'Lead Rapper', 'Rap') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (9, 'Sub Rapper', 'Rap') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (10, 'Leader', 'Specialty') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (11, 'Maknae', 'Specialty') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (12, 'Visual', 'Image') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (13, 'Center', 'Image') ON CONFLICT DO NOTHING;
INSERT INTO api.positions (position_id, name, category) VALUES (14, 'Face of the Group', 'Image') ON CONFLICT DO NOTHING;
-- idol_positions
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (1, 10) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (1, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (1, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (1, 12) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (2, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (2, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (2, 9) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (3, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (4, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (5, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (6, 7) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (6, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (6, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (7, 8) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (7, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.idol_positions (idol_id, position_id) VALUES (7, 11) ON CONFLICT DO NOTHING;
-- songs
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (1, 'Why Did You Come To My Home? (우리 집에 왜 왔니)', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (2, 'Why Did You Come To My Home? (우리 집에 왜 왔니) (Inst.)', 1, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (3, 'Superstar Superman', 2, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (4, 'Love Shake', 2, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (5, 'I Like You (나도 너처럼)', 2, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (6, 'Shut Up', 2, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (7, 'Love Shake (DJ Stereo Club Mix)', 2, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (8, 'Love Shake (Inst.)', 2, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (9, 'Welcome to Dream', 3, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (10, 'Chase Me', 3, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (11, 'Emotion', 3, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (12, 'Chase Me (Inst.)', 3, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (13, 'My Toys', 4, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (14, 'GOOD NIGHT', 4, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (15, 'Lullaby', 4, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (16, 'GOOD NIGHT (Inst.)', 4, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (17, 'Before & After (Intro)', 5, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (18, 'Fly High', 5, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (19, 'Wake Up', 5, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (20, 'Sleep-walking', 5, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (21, '괜찮아!', 5, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (22, 'Fly High (Inst.)', 5, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (23, 'Full Moon', 6, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (24, 'Full Moon (Inst.)', 6, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (25, 'INSIDE - OUTSIDE (Intro)', 7, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (26, 'YOU AND I', 7, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (27, 'Mayday', 7, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (28, 'Which a star', 7, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (29, 'Scar', 7, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (30, 'YOU AND I (Inst.)', 7, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (31, 'Intro', 8, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (32, 'What', 8, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (33, 'Wonderland', 8, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (34, 'Trap', 8, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (35, 'July 7th', 8, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (36, 'What (Inst.)', 8, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (37, 'What - Japanese Ver.', 9, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (38, 'Chase Me - Japanese Ver.', 9, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (39, 'I Miss You', 9, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (40, 'Over the Sky', 10, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (41, 'Over the Sky (Inst.)', 10, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (42, 'Intro', 11, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (43, 'PIRI', 11, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (44, 'Diamond', 11, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (45, 'And there was no one left', 11, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (46, 'Daydream', 11, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (47, 'PIRI (Inst.)', 11, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (48, 'PIRI - Fue wo Fuke - Japanese Ver.', 12, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (49, 'Good Night - Japanese Ver.', 12, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (50, 'Wonderland - Japanese Ver.', 12, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (51, 'Intro', 13, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (52, 'Breaking Out', 13, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (53, 'My Way ~ Kono Michi no Sakie ~', 13, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (54, 'Chase Me - Japanese Ver.', 13, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (55, 'Good Night - Japanese Ver.', 13, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (56, 'Wonderland - Japanese Ver.', 13, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (57, 'Piri ~ Fue wo Fuke ~ - Japanese Ver.', 13, 7) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (58, 'What - Japanese Ver.', 13, 8) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (59, 'I Miss You', 13, 9) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (60, 'Mata Hitori ni Natta - Japanese Ver.', 13, 10) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (61, 'You and I - Japanese Ver.', 13, 11) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (62, 'Outro', 13, 12) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (63, 'Intro', 14, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (64, 'Deja Vu', 14, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (65, 'The curse of the Spider', 14, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (66, 'Silent Night', 14, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (67, 'Polaris', 14, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (68, 'Deja Vu (Japanese Version)', 14, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (69, 'Intro', 15, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (70, 'Scream', 15, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (71, 'Tension', 15, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (72, 'Red Sun', 15, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (73, 'Black Or White', 15, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (74, 'Jazz Bar', 15, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (75, 'SAHARA', 15, 7) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (76, 'In The Frozen', 15, 8) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (77, 'Daybreak', 15, 9) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (78, 'Full Moon', 15, 10) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (79, 'Over the Sky (CD Only)', 15, 11) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (80, 'Outro', 15, 12) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (81, 'Scream (Inst.)', 15, 13) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (82, 'Paradise (Siyeon Solo)', 15, 14) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (83, 'Endless Night', 16, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (84, 'Over The Sky - Japanese Ver.', 16, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (85, 'Silent Night - Japanese Ver.', 16, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (86, 'Be the Future (with AleXa, IN2IT)', 17, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (87, 'Be the Future (Inst.)', 17, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (88, 'R.o.S.E BLUE (Prod ESTi)', 18, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (89, 'R.o.S.E BLUE (Prod ESTi) (Inst.)', 18, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (90, 'Intro', 19, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (91, 'BOCA', 19, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (92, 'Break The Wall', 19, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (93, 'Can''t get you out of my mind', 19, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (94, 'Dear', 19, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (95, 'BOCA (Inst.)', 19, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (96, 'No More', 20, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (97, 'Eclipse (TV Size)', 21, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (98, 'Intro', 22, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (99, 'Odd Eye', 22, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (100, 'Wind Blows', 22, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (101, 'Poison Love', 22, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (102, '4 Memory', 22, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (103, 'New Days', 22, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (104, 'Odd Eye (Inst.)', 22, 7) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (105, 'Eclipse', 23, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (106, 'No More', 23, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (107, 'Don''t Light My Fire', 23, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (108, 'Eclipse (Inst.)', 23, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (109, 'No More (Inst.)', 23, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (110, 'Don''t Light My Fire (Inst.)', 23, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (111, 'Shadow', 24, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (112, 'Shadow (Slow Ver.)', 24, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (113, 'Intro', 25, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (114, 'BEcause', 25, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (115, 'Airplane', 25, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (116, 'Whistle', 25, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (117, 'Alldaylong', 25, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (118, 'A Heart of Sunflower', 25, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (119, 'Intro : Save Us', 26, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (120, 'Locked Inside A Door', 26, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (121, 'Maison', 26, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (122, 'Starlight', 26, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (123, 'Together', 26, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (124, 'Always (널 위해)', 26, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (125, 'Skit : The Seven Doors', 26, 7) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (126, 'Cherry (Real Miracle) - JiU solo', 26, 8) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (127, 'No Dot - SuA solo', 26, 9) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (128, 'Entrancing (황흘경 極夜) - Siyeon solo', 26, 10) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (129, 'Winter (한겨울 寒冬) - Handong Solo', 26, 11) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (130, 'For - Yoohyeon solo', 26, 12) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (131, 'Beauty Full - Dami solo', 26, 13) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (132, 'Playground - Gahyeon solo', 26, 14) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (133, 'Intro : Chaotical X', 27, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (134, 'Vision', 27, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (135, 'Fairytale', 27, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (136, 'Some Love', 27, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (137, 'Rainy Day (이 비가 그칠 때면)', 27, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (138, 'Outro : Mother Nature', 27, 6) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (139, 'Reason', 28, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (140, 'Reason (Inst.)', 28, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (141, 'Intro : From us', 29, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (142, 'BONVOYAGE', 29, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (143, 'DEMIAN', 29, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (144, 'Propose', 29, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (145, 'To. Yo', 29, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (146, 'BONVOYAGE (Farewell Ver.)', 30, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (147, 'Intro : This My Fashion', 31, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (148, 'OOTD', 31, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (149, 'Rising', 31, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (150, 'Shatter', 31, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (151, 'We Are Young', 31, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (152, 'Lullaby (2024 Concert ver.)', 32, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (153, 'The curse of the Spider (2024 Concert ver.)', 32, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (154, 'Intro : 7'' Dreamcatcher', 33, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (155, 'JUSTICE', 33, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (156, 'STØMP!', 33, 3) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (157, '2 Rings', 33, 4) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (158, 'Fireflies', 33, 5) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (159, 'My Christmas Sweet Love', 34, 1) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (160, 'Jazz Bar (Carol ver.)', 34, 2) ON CONFLICT DO NOTHING;
INSERT INTO api.songs (song_id, song_name, album_id, track_number) OVERRIDING SYSTEM VALUE VALUES (161, 'Wonderland (Carol ver.)', 34, 3) ON CONFLICT DO NOTHING;

-- Sync identity/sequence values
SELECT setval('api.albums_album_id_seq', 34, true);
SELECT setval('api.groups_group_id_seq', 1, true);
SELECT setval('api.idols_idol_id_seq', 7, true);
SELECT setval('api.positions_position_id_seq', 14, true);
SELECT setval('api.songs_song_id_seq', 161, true);
